Repository fdnd-agency/visual-thinking, pull requests merged in 2024-06, with the labels that each got.

#171 🎨 Dry button name
  src/lib/organisms/methodHeader.svelte
Labels: should have, bugs

#173 :fire: Add loading spinner on form sumbission
  src/lib/molecules/filter.svelte
  static/styles/global.css
Labels: should have, bouwen

#178 ♻️Refactored background-color breadcrumb
  src/routes/artikelen/+page.svelte
Labels: must have, bouwen

#175 ♻️ Refactoring navigation naming
  src/lib/organisms/methodHeader.svelte
Labels: must have, bouwen, bugs

#176 💄Static footer logo
  src/lib/molecules/footer.svelte
Labels: must have, bouwen

#177 🐛Removed spacing header
  src/lib/organisms/methodHeader.svelte
Labels: bouwen, bugs

#182 🐛 Data ophalen methods error
  src/lib/organisms/methodHeader.svelte
  src/lib/queries/method.js
  src/routes/tekenmethodes/[slug]/+page.svelte
Labels: must have, bugs

#179 💄 Focus and hover state
  src/lib/molecules/filter.svelte
  src/lib/organisms/articles.svelte
  src/lib/organisms/methods.svelte
Labels: must have, bouwen

#180 💄 Link styling articles
  static/styles/global.css
Labels: must have, bouwen

#183 ♻️ New button name and some styling
  src/lib/organisms/methodHeader.svelte
Labels: must have, bugs

#185 ♻️ Toevoegen van .env file
  example.env
Labels: should have, integreren
