Repository fdnd-agency/visual-thinking, pull requests merged in 2025-04, with the labels that each got.

#329 adding hsl #324
  static/styles/global.css
Labels: Refactor

#330 Dev indenting #309
  src/lib/atoms/Hexagon.svelte
  src/lib/atoms/breadcrumb.svelte
  src/lib/molecules/filter.svelte
  src/lib/molecules/footer.svelte
  src/lib/molecules/header.svelte
  src/lib/molecules/introduction.svelte
  src/lib/molecules/steps.svelte
  src/lib/molecules/tagsPlan.svelte
  src/lib/organisms/homepage.svelte
  src/lib/organisms/knowledgeClips.svelte
  src/lib/organisms/methodHeader.svelte
  src/lib/organisms/methods.svelte
  src/lib/organisms/miniCourses.svelte
Labels: Integreren

#341 Dev refactor iconlibrary #315
  src/app.html
  src/lib/atoms/Hexagon.svelte
  src/lib/atoms/Icons.svelte
  src/lib/atoms/icons/iconCommunicate.svelte
  src/lib/atoms/icons/iconCreativeThinking.svelte
  src/lib/atoms/icons/iconLearnAboutOthers.svelte
  src/lib/atoms/icons/iconLearnAboutYourself.svelte
  src/lib/atoms/icons/iconOrganise.svelte
  src/lib/atoms/icons/iconResearch.svelte
  src/lib/index.js
  src/lib/molecules/footer.svelte
  src/lib/molecules/header.svelte
  src/lib/organisms/drawingSpace.svelte
  src/lib/organisms/homepage.svelte
  src/lib/organisms/knowledgeClips.svelte
  static/images/arrows.svg
  static/images/author.svg
  static/images/category.svg
  static/images/duration.svg
  static/images/favicon.svg
  static/images/instagram.svg
  static/images/linkedin.svg
  static/images/man.png
  static/images/man.svg
  static/images/materials.svg
  static/images/pencil-cursor.svg
  static/images/pencil.png
  static/images/pencil.svg
  static/images/visual-thinking-hbo-logo-footer.svg
  static/images/youtube.svg
  static/styles/global.css
Labels: Integreren, Testen

#346 adding global automatic colour scheme
  src/lib/atoms/Hexagon.svelte
  src/lib/atoms/Icons.svelte
  src/lib/atoms/blogButton.svelte
  src/lib/atoms/breadcrumb.svelte
  src/lib/molecules/filter.svelte
  src/lib/molecules/footer.svelte
  src/lib/molecules/header.svelte
  src/lib/molecules/steps.svelte
  src/lib/molecules/tagsPlan.svelte
  src/lib/organisms/articles.svelte
  src/lib/organisms/drawingSpace.svelte
  src/lib/organisms/homepage.svelte
  src/lib/organisms/knowledgeClips.svelte
  src/lib/organisms/methodHeader.svelte
  src/lib/organisms/methods.svelte
  src/lib/organisms/miniCourses.svelte
  src/routes/artikelen/+page.svelte
  src/routes/artikelen/[slug]/+page.svelte
  src/routes/minicursussen/+page.svelte
  src/routes/minicursussen/[slug]/+page.svelte
  src/routes/over/+page.svelte
  src/routes/tekenmethodes/+page.svelte
  src/routes/tekenmethodes/[slug]/+page.svelte
  src/routes/tekenmethodes/[slug]/stappenplan/+page.svelte
  src/routes/tekenmethodes/[slug]/voorbeelden/+page.svelte
  static/styles/global.css
Labels: Bouwen, Integreren
